from .models.JerarquiaAcad import JerarquiaAcad
from .models.Institucion import Institucion
from .models.Facultad import Facultad
from .models.Escuela import Escuela
from .models.Carrera import Carrera
from .models.NaturalPerson import NaturalPerson
from homend_configs.models.UnidadMedida import UnidadMedida
from homend_configs.models.Cliente import Cliente
from .models.Usuario import Usuario
from .models.Categoria import Categoria
#from homend_configs.models.Usuario import Usuario
